name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  # BuildAndTest:
  #   runs-on: ubuntu-latest
  #   name: Run Tests
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@master
  #     - name: Install dependencies
  #       run: dotnet restore
  #     - name: Build
  #       run: dotnet build --configuration Release --no-restore
  #     - name: Test
  #       run: dotnet test --no-restore --verbosity normal
  BuildAndPublish:
    needs: BuildAndTest
    runs-on: ubuntu-latest
    name: Update NuGet 
    steps:
      - name: Get Package version
        id: package_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: PDDLSharp/PDDLSharp.csproj
      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "PDDLSharp/bin/Release/*.nupkg"
          tag: ${{ steps.test.package_version.version }}

